# docker compose up --build --force-recreate --remove-orphans

services:
  # docker run --rm -it -v $(pwd):/app -w /app node:18 npx nuxi@latest init nuxt3
  nuxt3:
    image: node:22.6.0
    working_dir: /app
    command: bash -c "yarn install && yarn dev"
    environment:
      NUXT3_PORT: 3000
    ports:
      - ${NUXT3_PORT:-3000}:3000
    volumes:
      - ./nuxt3:/app
